version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  app:
    build:
      dockerfile: ./docker/Dockerfile
    ports:
      - 3333:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  phpmyadmin:
    links:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - 3334:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=1024M
      - MAX_EXECUTION_TIME=3000